<?php

// View file voor wachtwoord vergeten formulier.

?>

<html>
<head>
    <title>Login</title>
</head>
<body>

<?php if(isset($_SESSION['message'])): ?>
    <div class="message">
        <?php echo $_SESSION['message']; ?>
    </div>
<?php endif ?>

<form method="POST" action="index.php?action=forgotPassword">
    <label for="email">email</label>
    <input type="text" name="email" id="email" value="" />

    <button type="submit">Verstuur link</button>
</form>

</body>
</html>