<?php

// View file voor wachtwoord reset formulier.
if (!canResetPassword()) {
    $_SESSION['message'] = 'Een onbekende fout heeft opgetreden probeer het opnieuw';
    header('location:index.php');
}
?>

<html>
<head>
    <title>Reset wachtwoord</title>
</head>
<body>

<?php if(isset($_SESSION['message'])): ?>
    <div class="message">
        <?php echo showMessages(); ?>
    </div>
<?php endif ?>

<form method="POST" action="index.php?action=resetPassword">

    <input type="hidden" name="email" value="<?php echo $_GET['email']?>" />
    <input type="hidden" name="token" value="<?php echo $_GET['token']; ?>" />

    <label for="password">Wachtwoord</label>
    <input type="password" name="password" id="password" value="" />

    <label for="password_confirmation">Wachtwoord herhalen</label>
    <input type="password" name="password_confirmation" id="password_confirmation" value="" />

    <button type="submit">Wachtwoord resetten</button>
</form>

</body>
</html>