# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Server
env:
  ENV_FILE: |
    ${{ secrets.SERVER_ENV }}

on:
  push:
    branches:
      - Server
  pull_request:
    branches: 
      - Server
jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.PAT }}
    - run: npm i
    - run: echo -en $ENV_FILE > Server2.0/.env
